In [1]:
from sklearn.model_selection import train_test_split
import numpy as np
n = 200
X, y = np.arange(n).reshape((int(n/2), 2)), range(int(n/2)) # generate toy data set X with labels Y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # create a training and testing split

In [2]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

In [3]:
len(X_train)

60

In [4]:
len(X_val)

20

In [5]:
len(X_test)

20

In [6]:
X_train

array([[144, 145],
       [  2,   3],
       [ 30,  31],
       [136, 137],
       [ 16,  17],
       [ 74,  75],
       [108, 109],
       [196, 197],
       [132, 133],
       [178, 179],
       [150, 151],
       [102, 103],
       [192, 193],
       [158, 159],
       [ 96,  97],
       [ 32,  33],
       [ 42,  43],
       [ 38,  39],
       [100, 101],
       [ 56,  57],
       [142, 143],
       [ 84,  85],
       [130, 131],
       [ 72,  73],
       [ 18,  19],
       [104, 105],
       [ 80,  81],
       [ 12,  13],
       [172, 173],
       [188, 189],
       [ 92,  93],
       [184, 185],
       [ 10,  11],
       [ 50,  51],
       [198, 199],
       [162, 163],
       [122, 123],
       [ 54,  55],
       [ 86,  87],
       [ 28,  29],
       [ 64,  65],
       [ 94,  95],
       [ 34,  35],
       [120, 121],
       [118, 119],
       [ 58,  59],
       [174, 175],
       [128, 129],
       [ 26,  27],
       [176, 177],
       [116, 117],
       [ 68,  69],
       [ 52,

In [7]:
X_val

array([[ 48,  49],
       [110, 111],
       [ 14,  15],
       [  6,   7],
       [ 70,  71],
       [124, 125],
       [ 22,  23],
       [182, 183],
       [138, 139],
       [170, 171],
       [194, 195],
       [ 76,  77],
       [  4,   5],
       [156, 157],
       [ 46,  47],
       [134, 135],
       [164, 165],
       [168, 169],
       [114, 115],
       [112, 113]])

In [8]:
X_test

array([[166, 167],
       [106, 107],
       [140, 141],
       [ 90,  91],
       [ 88,  89],
       [ 78,  79],
       [ 44,  45],
       [160, 161],
       [ 20,  21],
       [  0,   1],
       [ 36,  37],
       [ 60,  61],
       [146, 147],
       [ 66,  67],
       [180, 181],
       [  8,   9],
       [152, 153],
       [154, 155],
       [ 24,  25],
       [ 62,  63]])